#! /bin/sh

case "$1" in
  start)
    echo "Starting aesdsocket"
    start-stop-daemon -S -o --exec /usr/bin/aesdsocket -- -d
    ;;
  stop)
    echo "Stopping aesdsocket"
    start-stop-daemon -K -o -n aesdsocket --retry 11
    ;;
  *)
    echo "Usage: $0 {start|stop}"
  exit 1
esac

exit 0
